name: single_view_entropy
view_mode: entropy
img_size: 224
patch_size: 16
in_chans: 1
num_classes: 18
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4.0
fusion_layers: []
fusion_alpha: 1.0
cross_weights: {}
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
pretrained: true
